### ISSUE TITLE
RuntimeException: unknown object tag -84

### ISSUE THREAD

**Issue by dmassart** [ErikTromp/Tuktu#62]
On macOS Sierra 10.12.3 using java 1.8.0_101, the latest source compiles fine but when trying to run it I get the following Runtime Exception:

! @73394nkep - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[RuntimeException: unknown object tag -84]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:166) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.10.jar:2.3.10]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.8.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.10.jar:2.3.10]
	at scala.util.Success.flatMap(Try.scala:231) ~[scala-library-2.11.8.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.10.jar:2.3.10]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.8.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.8.jar:na]
Caused by: java.lang.RuntimeException: unknown object tag -84
	at org.nustaq.serialization.FSTObjectInput.instantiateSpecialTag(FSTObjectInput.java:430) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:360) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:327) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:307) ~[fst-2.47.jar:na]
	at globals.DBGlobal.onStart(DBGlobal.scala:56) ~[na:na]
	at Global$$anonfun$onStart$16.apply(global.scala:117) ~[na:na]
	at Global$$anonfun$onStart$16.apply(global.scala:117) ~[na:na]
	at scala.collection.immutable.List.foreach(List.scala:381) ~[scala-library-2.11.8.jar:na]
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35) ~[scala-library-2.11.8.jar:na]
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45) ~[scala-library-2.11.8.jar:na]
	at Global$.onStart(global.scala:117) ~[na:na]
	at play.api.GlobalPlugin.onStart(GlobalSettings.scala:220) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.10.jar:2.3.10]
	at scala.collection.immutable.List.foreach(List.scala:381) ~[scala-library-2.11.8.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.Play$.start(Play.scala:90) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157) ~[play_2.11-2.3.10.jar:2.3.10]
	... 14 common frames omitted

**Comment by ErikTromp** [comment]
Remove TuktuDB's contents (db/data).
